# Generated by Django 5.2.13 on 2026-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remarcabledemo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="categories", to="remarcabledemo.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(related_name="tags", to="remarcabledemo.tag"),
        ),
    ]
