# Generated by Django 5.2.13 on 2026-04-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remarcabledemo", "0002_alter_product_category_alter_product_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products", to="remarcabledemo.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(
                related_name="products", to="remarcabledemo.tag"
            ),
        ),
    ]
